apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-server
  labels:
    app: verification-server
metadata:
  name: verification-server
  labels:
    app: verification-server
metadata:
  name: verification-server
  labels:
    app: verification-server
  labels:
    {{- include "verification-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
      app: verification-server
  template:
    metadata:
      labels:
        app: verification-server
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "verification-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      secretName: my-secret
      {{- end }}
      serviceAccountName: default
      securityContext:
        runAsUser: 1000
      containers:
        - name: server-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.command }}
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
