name: Build Keploy Binary

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: go build -tags=viper_bind_struct -o kTestBuild

      - name: Upload Keploy Binary as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: keploy-binary
          path: kTestBuild

  test:
    needs: build
    uses: ./.github/workflows/test_stage.yml

  test-ginApp:
    needs: build
    uses: ./.github/workflows/test-ginApp.yml  

  check_status:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Test Status
        run: echo "Test script status code ${{ needs.test.outputs.test_status }}"

