name: Build Keploy Binary

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: go build -tags=viper_bind_struct -cover -o keployB

      - name: Upload Keploy Binary as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: keploy-binary
          path: keployB

# Add Jobs for testing different applications here.          
  test-go-mongo-1:
    needs: build
    uses: ./.github/workflows/test-go-mongo-1.yml  

  test-go-mongo-2:
    needs: build
    uses: ./.github/workflows/test-go-mongo-2.yml    


# Wait for all the test workflows before getting the coverage
  wait-for-coverage:
    needs: [test-go-mongo-1, test-go-mongo-2]
    runs-on: ubuntu-latest
    steps:
      - name: wait for all workflows
        run: echo "All workflows are completed, Now calculating the coverage"

  get-coverage:
    needs: wait-for-coverage
    runs-on: ubuntu-latest
    uses: ./.github/workflows/coverage_stage.yml      

