name: Build keploy binary

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: go build -tags=viper_bind_struct -o kTestBuild

      - name: Trigger Testing Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Test Stage
          inputs: '{"binary_path": "kTestBuild"}'
