name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   pull_request_target:
#     types: [assigned, opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go test -coverpkg=./... -coverprofile=coverage.tmp.txt -covermode=atomic ./...
          cat coverage.tmp.txt | grep -v -e "generated.go" -e "_gen.go" > coverage.txt
        env:
          KEPLOY_API_KEY: 81f83aeeedddf453966347dc136c66
          KEPLOY_ENABLE_DEDUP: true

#       - uses: codecov/codecov-action@v2
#         with:
#           files: ./coverage.txt
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.txt -service=github
