name: Go

on:
  push:
    branches: [ main ]

jobs:

  verify_cla:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA is signed
        uses: cla-assistant/github-action@v2.1.3-beta
      - name: Proceed only if CLA signed
        if: failure()

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - - name: Import CLA files and entities
        uses: cla-assistant/setup@v2
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Build
        run: |
          go build -v ./...

      - name: Build arm 
        run: GOOS=linux GOARCH=arm64 go build -v ./...
