name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Build
        run: |
          go build -v ./...
