name: Release
on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: |
          go test -coverpkg=./... -coverprofile=coverage.tmp.txt -covermode=atomic ./...
          cat coverage.tmp.txt | grep -v -e "generated.go" -e "_gen.go" | grep -v -e "services.pb.go" -e "services_grpc.pb.go" > coverage.txt
        env:
          KEPLOY_API_KEY: 81f83aeeedddf453966347dc136c66
          ENABLE_DEDUP: false

      - name: Test-withDeDupEnabled
        run: |
          go test -coverpkg=./... -coverprofile=coverage.tmp.txt -covermode=atomic ./...
          cat coverage.tmp.txt | grep -v -e "generated.go" -e "_gen.go" | grep -v -e "services.pb.go" -e "services_grpc.pb.go" > coverage.txt
        env:
          KEPLOY_API_KEY: 81f83aeeedddf453966347dc136c66
          ENABLE_DEDUP: true
          ENABLE_TEST_EXPORT: false


      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.txt -service=github

      - name: Checkout UI
        uses: actions/checkout@v2
        with:
          repository: keploy/ui
          path: ui

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build web app
        run: |
          cd $GITHUB_WORKSPACE/ui
          npm install
          npm run build
          cp -r public $GITHUB_WORKSPACE/web
          rm -rf $GITHUB_WORKSPACE/ui
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
