name: Telemetry

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Keploy
        run: |
          go build -v ./...

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Setup java Sample project
        run: |
          git clone https://github.com/charankamarapu/Sample-Redis_Keploy.git &&
          curl 'https://repo1.maven.org/maven2/io/keploy/agent/1.2.7/agent-1.2.7.jar' --compressed --output Sample-Redis_Keploy/agent.jar -slient

      - name: Run Keploy and java project
        run: |
          go run ./cmd/server/main.go &
          sudo apt update &&
          sudo apt install maven -y &&
          cd Sample-Redis_Keploy &&
          mvn clean install &&
          export KEPLOY_MODE=test &&
          count=5
          for i in $(seq $count); do
            java -javaagent:${PWD}/agent.jar -jar target/SpringBoot-Redis-Example-0.0.1-SNAPSHOT.jar
          done
          cat /root/keploy-config/installation-id.yaml
