name: Test FlaskApp 2
on:
  workflow_call:

jobs:
  test-flask-mongo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Keploy Build Binary
        uses: actions/download-artifact@v4
        with:
          name: keploy-binary
          path: /usr/local/bin

      - name: Giving permission to binary
        run: |
          sudo chmod +x /usr/local/bin/keployB

      - name: Download the latest released binary of keploy
        run: |
          curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keployR

      - name: Get the pilot for tests and mocks assertion
        run: |
          curl --silent -o pilot --location "https://github.com/keploy/pilot/releases/latest/download/pilot_linux_amd64" && 
          sudo chmod a+x pilot && sudo mkdir -p /usr/local/bin && sudo mv pilot /usr/local/bin

      - name: Checkout to the samples-python repository
        uses: actions/checkout@v4
        with:
          repository: keploy/samples-python
          ref: main
          path: samples-python

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          cd samples-python/flask-mongo
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Add noisy fields in the config file
        run: |
          echo "You can add the noisy fields in the config file if any."

      - name: Run testing script for flask-mongo application
        uses: ./.github/actions/tester
        with:
          working-directory: samples-python/flask-mongo
          command: |
            . venv/bin/activate
            python3 app.py
          delay: 7
          keploy-record-bin: /usr/local/bin/keployR
          keploy-test-bin: /usr/local/bin/keployB
          mode: 1
