name: Test Stage
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Keploy Binary"]  # Ensure this name matches exactly with the build workflow's name
    types:
      - completed

jobs:
  test-go-mongo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Keploy Binary
        uses: actions/download-artifact@v2
        with:
          name: keploy-binary
          path: /usr/local/bin

      - name: Giving permission to binary
        run: |
          sudo chmod +x /usr/local/bin/kTestBuild

      - name: Checkout the samples-go repository
        uses: actions/checkout@v2
        with:
          repository: keploy/samples-go
          path: samples-go

      - name: Run samples-go application
        run: |
          cd samples-go/gin-mongo
          source ./../../.github/workflows/test-bench-workflow-scripts/mongo/go-mongo-linux-1.sh
