name: w1

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: go build -tags=viper_bind_struct -o kTestBuild

      - name: Trigger Test Stage Workflow
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/test_stage.yml/dispatches" \
            -d '{"ref":"${{ github.ref }}", "inputs": {"keploy_binary":"kTestBuild"}}'
